name: build and deploy image to docker.hub

on:
  workflow_run:
    workflows: [ Build and Verify ]
    types:
      - completed

  workflow_dispatch:
    branches: [ main ]

jobs:
  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and deploy image
        run: mvn compile jib:build -P build-docker -Djib.to.auth.username=${{ secrets.DOCKERHUB_USER }} -Djib.to.auth.password=${{ secrets.DOCKERHUB_TOKEN }}
